{
  wlib,
  lib,
  pkgs,
  config,
  ...
}:
let
  inherit (lib) mkOption mkIf types;
  configAtom =
    with types;
    oneOf [
      bool
      int
      wlib.types.stringable
    ];

  renderSingleOption =
    name: value:
    let
      isShort = builtins.stringLength name == 1;
      prefix = if isShort then "-" else "--";
    in
    if lib.isBool value then
      if value then
        "${prefix}${name}"
      else if isShort then
        ""
      else
        "--no-${name}"
    else
      "${prefix}${name}=${toString value}";

  renderMultipleValueOption =
    name: value: lib.concatMapStringsSep "\n" (renderSingleOption name) (lib.toList value);

  renderSettings = lib.concatMapAttrsStringSep "\n" renderMultipleValueOption;
in
{
  imports = [ wlib.modules.default ];
  options = {
    settings = mkOption {
      type = with types; attrsOf (either configAtom (listOf configAtom));
      default = { };
      description = ''
        Options to add to ripgrep settings file.
        See <https://github.com/BurntSushi/ripgrep/blob/master/GUIDE.md#configuration-file>
        for options.
      '';
      example = lib.literalExpression ''
        {
          hidden = true;
          # Similar to running -uuu
          u = builtins.genList (lib.const true) 3;
        }'';
    };
    ignores = mkOption {
      type = types.lines;
      default = "";
      description = "Glob patterns to add to ripgrep ignores file.";
    };
  };

  config = {
    package = pkgs.ripgrep;
    env."RIPGREP_CONFIG_PATH" = config.constructFiles.renderedSettings.path;
    flags."--ignore-file" = mkIf (config.ignores != "") config.constructFiles.renderedIgnores.path;
    constructFiles = {
      renderedSettings = {
        relPath = "${config.binName}-settings";
        content = ''
          # Generated by nix-wrapper-modules.
          # See https://github.com/BurntSushi/ripgrep/blob/master/GUIDE.md#configuration-file
          ${renderSettings config.settings}
        '';
      };
      renderedIgnores = {
        relPath = "${config.binName}-ignores";
        content = config.ignores;
      };
    };
    meta.maintainers = [ wlib.maintainers.Nadim147c ];
  };
}
